import Image from 'next/image'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'

import Container from '../components/Container'
import Footer from '../components/Footer'
import Header from '../components/Header'
import location from './location.png'

export default function ContactPage() {
  return (
    <>
      <Header />
      <main className="py-8">
        <Container>
          <h1 className="text-3xl font-extrabold">Contact Us</h1>
          <p className="my-8">
            This is a demo page generated by Vercel v0, and the location image
            was generated by DALL-E 3 on ChatGPT. This contact form does not
            work. The contact information and location below does not exist.
          </p>
          <div className="space-y-8">
            <div className="rounded border border-slate-200 p-6 dark:border-slate-800">
              <form className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="name">Name</Label>
                  <span className="text-red-700"> *</span>
                  <Input id="name" placeholder="Enter your name" required />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="email">Email</Label>
                  <span className="text-red-700"> *</span>
                  <Input
                    id="email"
                    placeholder="Enter your email"
                    type="email"
                    required
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="subject">Subject</Label>
                  <Input id="subject" placeholder="Enter your subject" />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="message">Message</Label>
                  <span className="text-red-700"> *</span>
                  <Textarea
                    className="min-h-[100px]"
                    id="message"
                    placeholder="Enter your message"
                    required
                  />
                </div>
                <Button type="submit">Submit</Button>
              </form>
            </div>
            <div className="space-y-4">
              <h2 className="text-xl font-bold">Contact Information</h2>
              <div className="space-y-2">
                <p className="text-sm">1234 Some Street</p>
                <p className="text-sm">City, State, 12345</p>
                <p className="text-sm">Phone: (123) 456-7890</p>
                <p className="text-sm">Email: info@website.com</p>
              </div>
            </div>
            <div className="space-y-4">
              <h2 className="text-xl font-bold">Location</h2>
              <div className="overflow-hidden rounded-lg">
                <Image alt="Map" src={location} />
              </div>
            </div>
          </div>
        </Container>
      </main>
      <Footer />
    </>
  )
}
