import './globals.css'

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL
const siteName = process.env.NEXT_PUBLIC_SITE_NAME
const twitterHandle = process.env.NEXT_PUBLIC_TWITTER_HANDLE

const description = 'Generated by create next app'
const ogImage = ''

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/favicon/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon/favicon-16x16.png"
        />
        <link rel="manifest" href="/favicon/site.webmanifest" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:site" content={twitterHandle} />
        <title>{siteName}</title>
        <meta property="og:title" content={siteName} />
        <meta name="description" content={description} />
        <meta property="og:description" content={description} />
        <meta property="og:image" content={ogImage} />
        <meta property="og:type" content="website" />
        <meta property="og:url" content={siteUrl} />
        <link rel="canonical" href={siteUrl} />
      </head>
      <body>{children}</body>
    </html>
  )
}
